name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu для деплоя

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: npm install

      # Шаг 4: Построение проекта
      - name: Build project
        run: npm run build

      # Шаг 5: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Это переменная для доступа
          branch: gh-pages  
          folder: dist 
